### ISSUE TITLE
酷我源好像寄了 这下彻底无源可用了

### ISSUE THREAD

**Issue by catsimple** [UnblockNeteaseMusic/server#1153]
### Bug 描述

ERROR: (provider/match) Cannot read properties of undefined (reading 'list')
    TypeError: Cannot read properties of undefined (reading 'list')
        at /mnt/sda1/packages/unblocknode/precompiled/app.js:3:27473
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async u.cache (/mnt/sda1/packages/unblocknode/precompiled/app.js:2:1243)
        at async m (/mnt/sda1/packages/unblocknode/precompiled/app.js:3:28729)
        at async Promise.any (index 0)
        at async b (/mnt/sda1/packages/unblocknode/precompiled/app.js:3:29535)
        at async Promise.all (index 0)

### 日志内容

-

### 网易云音乐版本号

2.10.6

### 操作系统

Windows 11

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by ls148478** [comment]
我也遇到了这个问题 不过是qq音乐

**Comment by pan93412** [comment]
你可以試試看 Rust 的 kuwo 源看看是否可用，如果可用我再移植過來這裡：https://github.com/UnblockNeteaseMusic/server-rust/tree/main/engines/kuwo

**Comment by 1715173329** [comment]
> 你可以試試看 Rust 的 kuwo 源看看是否可用，如果可用我再移植過來這裡：https://github.com/UnblockNeteaseMusic/server-rust/tree/main/engines/kuwo

大概 rs 那边也需要更新了

**Comment by fmwww** [comment]
同样的问题+1

**Comment by catsimple** [comment]
> 同样的问题+1

最新的pull已经修复了，不过好像这次pull了以后不能像之前一样直接播放了，得启用endpoint了
