### ISSUE TITLE
ERROR: (hook) A error occurred in hook.request.before when hooking https://music.163.com/api/linux/forward.

### ISSUE THREAD

**Issue by wangsd01** [UnblockNeteaseMusic/server#205]
Ubuntu 18.04
NeteaseMusic 1.2

sudo node app.js -p 80:443 -f 103.126.92.133

INFO: (app) HTTP Server running @ http://0.0.0.0:80
INFO: (app) HTTPS Server running @ http://0.0.0.0:443
ERROR: (hook) A error occurred in hook.request.before when hooking https://music.163.com/api/linux/forward.
    TypeError: IV must be a buffer
        at new Decipheriv (crypto.js:267:16)
        at Object.createDecipheriv (crypto.js:627:10)
        at decrypt (/home/wang/github/server/precompiled/app.js:11150:29)
        at Object.decrypt (/home/wang/github/server/precompiled/app.js:11179:26)
        at request$1.read.then.then.body (/home/wang/github/server/precompiled/app.js:12385:45)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by pan93412** [comment]
@1715173329 API 疑似變動

**Comment by 1715173329** [comment]
应该说是加密方式！#79

**Comment by 1715173329** [comment]
fixed already
