### ISSUE TITLE
''ERROR: (provider/match) Unexpected token E in JSON at position 0

### ISSUE THREAD

**Issue by 4860575** [UnblockNeteaseMusic/server#271]
系统：debian10
node：v14.18.1
版本：commit d668fc6239ba6f4d334a1f07aa6dd575532404e8
启动方式：MIN_BR=320000 ENABLE_FLAC=true ENABLE_LOCAL_VIP=true node /home/G/UnblockNeteaseMusic-b/app.js -o pyncmd kuwo -p 5200:5201 -s >>/tmp/flac.log 2>&1 &
错误日志如下：

- ERROR (SongNotAvailable): (provider/match) This song "?" is not available in pyncmd
    SongNotAvailable: This song "?" is not available in pyncmd
        at getAudioFromSource (/home/G/UnblockNeteaseMusic-b/precompiled/app.js:10288:25)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERROR (SongNotAvailable): (provider/match) This song "?" is not available in pyncmd
    SongNotAvailable: This song "?" is not available in pyncmd
        at getAudioFromSource (/home/G/UnblockNeteaseMusic-b/precompiled/app.js:10288:25)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERROR (SongNotAvailable): (provider/match) This song "?" is not available in pyncmd
    SongNotAvailable: This song "?" is not available in pyncmd
        at getAudioFromSource (/home/G/UnblockNeteaseMusic-b/precompiled/app.js:10288:25)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:1447) UnhandledPromiseRejectionWarning: TypeError: getBuiltIn(...) is not a constructor
    at /home/G/UnblockNeteaseMusic-b/precompiled/app.js:10094:33
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1447) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1447) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
INFO: (provider/match) Replaced: [4263218] Eifersucht
    audioId: 4263218
    songName: "Eifersucht"
    url: "http://ck.sycdn.kuwo.cn/93f0bb6f6a0e14505138c483a5371ffb/616ba2cb/resource/n2/31/3/3883733505.mp3"
INFO: (provider/match) Replaced: [22587348] Last Christmas
    audioId: 22587348
    songName: "Last Christmas"
    url: "http://cg.sycdn.kuwo.cn/1ef845f502ebb400c3522aaa7e51f791/616ba2cb/resource/n2/40/65/1371630180.mp3"
ERROR (SongNotAvailable): (provider/match) This song "?" is not available in pyncmd
    SongNotAvailable: This song "?" is not available in pyncmd
        at getAudioFromSource (/home/G/UnblockNeteaseMusic-b/precompiled/app.js:10288:25)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
INFO: (provider/match) Replaced: [292587] 在劫难逃
    audioId: 292587
    songName: "在劫难逃"
    url: "http://gt.sycdn.kuwo.cn/f15205c50f9eeb62cc6187d822eb158c/616ba2cd/resource/n3/18/89/2037825402.mp3"
ERROR (SongNotAvailable): (provider/match) This song "?" is not available in pyncmd
    SongNotAvailable: This song "?" is not available in pyncmd
        at getAudioFromSource (/home/G/UnblockNeteaseMusic-b/precompiled/app.js:10288:25)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:1447) UnhandledPromiseRejectionWarning: TypeError: getBuiltIn(...) is not a constructor
    at /home/G/UnblockNeteaseMusic-b/precompiled/app.js:10094:33
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:1447) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
ERROR (SongNotAvailable): (provider/match) This song "?" is not available in pyncmd
    SongNotAvailable: This song "?" is not available in pyncmd
        at getAudioFromSource (/home/G/UnblockNeteaseMusic-b/precompiled/app.js:10288:25)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERROR: (provider/match) Unexpected token E in JSON at position 0
    SyntaxError: Unexpected token E in JSON at position 0
        at JSON.parse (<anonymous>)
        at /home/G/UnblockNeteaseMusic-b/precompiled/app.js:6805:64
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async CacheStorage.cache (/home/G/UnblockNeteaseMusic-b/precompiled/app.js:8893:28)
        at async getAudioFromSource (/home/G/UnblockNeteaseMusic-b/precompiled/app.js:10287:21)
(node:1447) UnhandledPromiseRejectionWarning: TypeError: getBuiltIn(...) is not a constructor
    at /home/G/UnblockNeteaseMusic-b/precompiled/app.js:10094:33
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:1447) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "http://kuwo.cn/search/list?key=Slippin%27Taylor%20Thrash"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "http://kuwo.cn/search/list?key=EifersuchtRammstein"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "http://kuwo.cn/search/list?key=Last%20ChristmasState%20Of%20The%20Heart"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "http://kuwo.cn/search/list?key=%E5%9C%A8%E5%8A%AB%E9%9A%BE%E9%80%83%E6%92%92%E5%A8%87"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "http://kuwo.cn/search/list?key=The%20RoseEmi%20Fujita"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "http://kuwo.cn/search/list?key=%E6%88%91%E5%B0%B1%E5%9C%A8%E4%BD%A0%E8%BA%AB%E8%BE%B9%E5%91%A8%E6%B2%BB%E5%B9%B3"

**Comment by pan93412** [comment]
@1715173329 疑似是 f969da1d5500a8819f78ae19f3a9b7f100d586ff 引入的 bug。你確認一下？

**Comment by 1715173329** [comment]
> @1715173329 疑似是 [f969da1](https://github.com/UnblockNeteaseMusic/server/commit/f969da1d5500a8819f78ae19f3a9b7f100d586ff) 引入的 bug。你確認一下？

这个问题一开始就有了，所以我才做了这个更改
不过显然似乎并没有真正起作用
Will check it later
