### ISSUE TITLE
IOS 无法使用，还有大佬可以帮忙解答下docker容器怎么选择特定的音乐源，他dokcer run 直接就是默认了

### ISSUE THREAD

**Issue by wper-golo** [UnblockNeteaseMusic/server#672]
这是我的docker容器日志 我觉得是app.js里面文件编写有bug，电脑端可以正常使用 
>ERROR (ProcessExitNotSuccessfully): (provider/yt-dlp) yt-dlp exited with 1, which is not zero.,
    ProcessExitNotSuccessfully: yt-dlp exited with 1, which is not zero.,
        at ChildProcess.<anonymous> (/app/app.js:3615:36),
        at ChildProcess.emit (node:events:526:28),
        at maybeClose (node:internal/child_process:1092:16),
        at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5),
    process: yt-dlp,
    exitCode: 1,
ERROR (ProcessExitNotSuccessfully): (provider/match) yt-dlp exited with 1, which is not zero.,
    ProcessExitNotSuccessfully: yt-dlp exited with 1, which is not zero.,
        at ChildProcess.<anonymous> (/app/app.js:3615:36),
        at ChildProcess.emit (node:events:526:28),
        at maybeClose (node:internal/child_process:1092:16),
        at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5),
    process: yt-dlp,
    exitCode: 1,
WARN: (spawn) [yt-dlp][stderr] WARNING: [youtube:search] <urlopen error [Errno 99] Address not available>. Retrying ...,
,
WARN: (spawn) [yt-dlp][stderr] WARNING: [youtube:search] <urlopen error [Errno 99] Address not available>. Retrying ...,
,
WARN: (spawn) [yt-dlp][stderr] WARNING: [youtube:search] <urlopen error [Errno 99] Address not available>. Retrying ...,
,
WARN: (spawn) [yt-dlp][stderr] WARNING: [youtube:search] <urlopen error [Errno 99] Address not available>. Retrying ...,
,
WARN: (spawn) [yt-dlp][stderr] WARNING: [youtube:search] <urlopen error [Errno 99] Address not available>. Retrying ...,
,
WARN: (spawn) [yt-dlp][stderr] WARNING: [youtube:search] <urlopen error [Errno 99] Address not available>. Retrying ...,
,
WARN: (spawn) [yt-dlp][stderr] ERROR: Unable to download API page: <urlopen error [Errno 99] Address not available> (caused by URLError(OSError(99, 'Address not available'))),
,
ERROR (ProcessExitNotSuccessfully): (provider/yt-dlp) yt-dlp exited with 1, which is not zero.,
    ProcessExitNotSuccessfully: yt-dlp exited with 1, which is not zero.,
        at ChildProcess.<anonymous> (/app/app.js:3615:36),
        at ChildProcess.emit (node:events:526:28),
        at maybeClose (node:internal/child_process:1092:16),
        at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5),
    process: yt-dlp,
    exitCode: 1,
ERROR (ProcessExitNotSuccessfully): (provider/match) yt-dlp exited with 1, which is not zero.,
    ProcessExitNotSuccessfully: yt-dlp exited with 1, which is not zero.,
        at ChildProcess.<anonymous> (/app/app.js:3615:36),
        at ChildProcess.emit (node:events:526:28),
        at maybeClose (node:internal/child_process:1092:16),
        at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5),
    process: yt-dlp,
    exitCode: 1,
WARN: (spawn) [yt-dlp][stderr] ERROR: Unable to download API page: <urlopen error [Errno 99] Address not available> (caused by URLError(OSError(99, 'Address not available'))),
,
ERROR (ProcessExitNotSuccessfully): (provider/yt-dlp) yt-dlp exited with 1, which is not zero.,
    ProcessExitNotSuccessfully: yt-dlp exited with 1, which is not zero.,
        at ChildProcess.<anonymous> (/app/app.js:3615:36),
        at ChildProcess.emit (node:events:526:28),
        at maybeClose (node:internal/child_process:1092:16),
        at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5),
    process: yt-dlp,
    exitCode: 1,
ERROR (ProcessExitNotSuccessfully): (provider/match) yt-dlp exited with 1, which is not zero.,
    ProcessExitNotSuccessfully: yt-dlp exited with 1, which is not zero.,
        at ChildProcess.<anonymous> (/app/app.js:3615:36),
        at ChildProcess.emit (node:events:526:28),
        at maybeClose (node:internal/child_process:1092:16),
        at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5),
    process: yt-dlp,
    exitCode: 1,
WARN: (spawn) [yt-dlp][stderr] ERROR: Unable to download API page: <urlopen error [Errno 99] Address not available> (caused by URLError(OSError(99, 'Address not available'))),
,
ERROR (ProcessExitNotSuccessfully): (provider/yt-dlp) yt-dlp exited with 1, which is not zero.,
    ProcessExitNotSuccessfully: yt-dlp exited with 1, which is not zero.,
        at ChildProcess.<anonymous> (/app/app.js:3615:36),
        at ChildProcess.emit (node:events:526:28),
        at maybeClose (node:internal/child_process:1092:16),
        at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5),
    process: yt-dlp,
    exitCode: 1,
ERROR (ProcessExitNotSuccessfully): (provider/match) yt-dlp exited with 1, which is not zero.,
    ProcessExitNotSuccessfully: yt-dlp exited with 1, which is not zero.,
        at ChildProcess.<anonymous> (/app/app.js:3615:36),
        at ChildProcess.emit (node:events:526:28),
        at maybeClose (node:internal/child_process:1092:16),
        at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5),
    process: yt-dlp,
    exitCode: 1,
WARN: (spawn) [yt-dlp][stderr] ERROR: Unable to download API page: <urlopen error [Errno 99] Address not available> (caused by URLError(OSError(99, 'Address not available'))),
,
ERROR (ProcessExitNotSuccessfully): (provider/yt-dlp) yt-dlp exited with 1, which is not zero.,
    ProcessExitNotSuccessfully: yt-dlp exited with 1, which is not zero.,
        at ChildProcess.<anonymous> (/app/app.js:3615:36),
        at ChildProcess.emit (node:events:526:28),
        at maybeClose (node:internal/child_process:1092:16),
        at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5),
    process: yt-dlp,
    exitCode: 1,
ERROR (ProcessExitNotSuccessfully): (provider/match) yt-dlp exited with 1, which is not zero.,
    ProcessExitNotSuccessfully: yt-dlp exited with 1, which is not zero.,
        at ChildProcess.<anonymous> (/app/app.js:3615:36),
        at ChildProcess.emit (node:events:526:28),
        at maybeClose (node:internal/child_process:1092:16),
        at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5),
    process: yt-dlp,
    exitCode: 1,

**Comment by 1715173329** [comment]
网络环境有问题。传参方法请见 readme。
