### ISSUE TITLE
yt-dlp源只能播放9秒

### ISSUE THREAD

**Issue by duhd1993** [UnblockNeteaseMusic/server#775]
有两种情况

```
Jul 06 00:28:29 bwh unblockneteasemusic[12923]: INFO: (spawn) running yt-dlp -f 140 --dump-json ytsearch1:我的时代 (Live) - 派伟俊
Jul 06 00:28:30 bwh unblockneteasemusic[12923]: INFO: (provider/match) Replaced: [1400391917] 我的时代 (Live)
Jul 06 00:28:30 bwh unblockneteasemusic[12923]:     audioId: 1400391917
Jul 06 00:28:30 bwh unblockneteasemusic[12923]:     songName: "我的时代 (Live)"
Jul 06 00:28:30 bwh unblockneteasemusic[12923]:     url: "http://upos-sz-mirrorhw.bilivideo.com/ugaxcode/m210607a212m7ai7em2dkv10xnq7udv0-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrN>
Jul 06 00:28:31 bwh unblockneteasemusic[12923]: ERROR: (provider/yt-dlp) Unexpected end of JSON input
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:     SyntaxError: Unexpected end of JSON input
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:         at JSON.parse (<anonymous>)
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:         at getUrl (/usr/local/UnblockNeteaseMusic/precompiled/app.js:2893:31)
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:         at runMicrotasks (<anonymous>)
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:         at processTicksAndRejections (node:internal/process/task_queues:96:5)
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:         at async search (/usr/local/UnblockNeteaseMusic/precompiled/app.js:2902:21)
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:         at async CacheStorage.cache (/usr/local/UnblockNeteaseMusic/precompiled/app.js:129:32)
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:         at async getAudioFromSource (/usr/local/UnblockNeteaseMusic/precompiled/app.js:2298:23)
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:         at async Promise.any (index 4)
Jul 06 00:28:31 bwh unblockneteasemusic[12923]: ERROR: (provider/match) Unexpected end of JSON input
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:     SyntaxError: Unexpected end of JSON input
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:         at JSON.parse (<anonymous>)
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:         at getUrl (/usr/local/UnblockNeteaseMusic/precompiled/app.js:2893:31)
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:         at runMicrotasks (<anonymous>)
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:         at processTicksAndRejections (node:internal/process/task_queues:96:5)
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:         at async search (/usr/local/UnblockNeteaseMusic/precompiled/app.js:2902:21)
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:         at async CacheStorage.cache (/usr/local/UnblockNeteaseMusic/precompiled/app.js:129:32)
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:         at async getAudioFromSource (/usr/local/UnblockNeteaseMusic/precompiled/app.js:2298:23)
Jul 06 00:28:31 bwh unblockneteasemusic[12923]:         at async Promise.any (index 4)
```
似乎就没获取到正确的json返回值，手动run没问题（关键词中间有空格需要加上引号，spawn应该不存在这个问题）

```
Jul 06 00:44:20 bwh unblockneteasemusic[12923]: INFO: (spawn) running yt-dlp -f 140 --dump-json ytsearch1:爱的飞行日记 (Live) - 杨瑞代
Jul 06 00:44:21 bwh unblockneteasemusic[12923]: INFO: (provider/match) Replaced: [1400391959] 爱的飞行日记 (Live)
Jul 06 00:44:21 bwh unblockneteasemusic[12923]:     audioId: 1400391959
Jul 06 00:44:21 bwh unblockneteasemusic[12923]:     songName: "爱的飞行日记 (Live)"
Jul 06 00:44:21 bwh unblockneteasemusic[12923]:     url: "http://upos-sz-mirrorhw.bilivideo.com/ugaxcode/m200827a21tk9tt5txmcwh13v7gmq7il-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrN>
Jul 06 00:44:24 bwh unblockneteasemusic[12923]: INFO: (spawn) running yt-dlp -f 140 --dump-json https://www.youtube.com/watch?v=P7IvYsQuZCc
```
搜索出来的这个完全不对，也没被用到

**Comment by duhd1993** [comment]
@pan93412 请问可以看看吗？

**Comment by duhd1993** [comment]
今天好像能搜到了，但是不能正常播放，拿到的url是完整的，但是播放的只有9s
```
[INFO: (spawn) running yt-dlp -f 140 --dump-json ytsearch1:Mojito - 周杰伦
INFO: (spawn) running yt-dlp -f 140 --dump-json https://www.youtube.com/watch?v=-biOGdYiF-I
INFO: (provider/match) Replaced: [1454811222] Mojito
    audioId: 1454811222
    songName: "Mojito"
    url: "https://rr6---sn-a5mlrnez.googlevideo.com/videoplayback?expire=1657624408&ei=-ALNYtTDI8vCkgan3pH4Dg&ip=111.111.111.111&id=o-AMJcL0sU9LYnrT07TD7mEe-n37Gy6aFbRuF4MGBEXxZm&itag=140&source=youtube&requiressl=yes&mh=6F&mm=31%2C29&mn=sn-a5mlrnez%2Csn-a5mekn6k&ms=au%2Crdu&mv=m&mvi=6&pl=20&initcwndbps=1251250&vprv=1&mime=audio%2Fmp4&gir=yes&clen=3049455&dur=188.383&lmt=1653628543790854&mt=1657602541&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAP5QZ_aGwXVnkOp5WNjV3SIxB-1eRsrzv4RXyrbHduPZAiAE8xyfs6nE_-4MGCahgRxyPUYVKLClTOd6m4kBhtiJ5g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgL4VuKjoZvNX7G66PjXA2VLpRqzQdh3bkBqT2KY8NQ8kCIQCIUNo1WQF3_j5VGL0UdhkAY8ZxTPWs8pmPUWpynBdz6g%3D%3D"
```

**Comment by overXsky** [comment]
同遇到此问题，怎么解决？

**Comment by pan93412** [comment]
最近很忙，沒空處理 UNM⋯⋯先把 yt-dlp 音源停用吧。

**Comment by duhd1993** [comment]
我这里Kugou这个源也不能用，搜了下找到这个API https://github.com/LanccBy2016/KugouDownload/blob/master/kugoudownload/Program.cs 可以用。需要的话可以PR

**Comment by pan93412** [comment]
@duhd1993 可以幫忙 PR 嗎，謝謝！❤️

可以的話也希望能幫忙也 PR 到 https://github.com/UnblockNeteaseMusic/server-rust

**Comment by duhd1993** [comment]
好的，不过我好像没看到人反馈kugou不能用，不确定是不是我的问题。

**Comment by catalpaaa** [comment]
除了bilibili 和 ytdlp之外的音源我在墙外都用不了

**Comment by ZhaofengWu** [comment]
同样遇到 ytdlp 只能播放九秒的问题，请问目前有解决方式吗？

**Comment by oishi81** [comment]
> 最近很忙，沒空處理 UNM⋯⋯先把 yt-dlp 音源停用吧。

请问如何停用yt-dlp音源？
我是用的node app.js

**Comment by myahmao** [comment]
yt-dlp命令可以把MP4在本地转成MP3，也就几秒钟的事。可以打开mp3文件播放吗，还是必须从json里面获得网页链接播放？

**Comment by pan93412** [comment]
> 新的ytdlp问题：
> 
> [litter.catbox.moe/3siebk.txt](https://litter.catbox.moe/3siebk.txt) [transfer.sh/6IdIXg/unm-debugging-output.txt](https://transfer.sh/6IdIXg/unm-debugging-output.txt)

都 Not Found 耶……

**Comment by pan93412** [comment]
> > > 新的ytdlp问题：
> > > [litter.catbox.moe/3siebk.txt](https://litter.catbox.moe/3siebk.txt) [transfer.sh/6IdIXg/unm-debugging-output.txt](https://transfer.sh/6IdIXg/unm-debugging-output.txt)
> > 
> > 
> > 都 Not Found 耶……
> 
> 旧的估计都过期了，这是最新的4/9/2023 10：51pm，你可以看下
> 
> [litter.catbox.moe/nyw8ug.txt](https://litter.catbox.moe/nyw8ug.txt) [transfer.sh/eB96OX/unm-debugging-output.txt](https://transfer.sh/eB96OX/unm-debugging-output.txt)

我看了一下，應該是你 `yt-dlp` 裝得有點問題。試試看 `pip install yt-dlp` 重裝？

**Comment by freeqimmy** [comment]
尝试了下2023.02.17版本，binary、linux standalone以及pip版本的都试了，结果都是只能播放9秒，问题没有解决

**Comment by EricYoung37** [comment]
我也遇到了，不使用严格模式`$node app.js -p 8080:8081 -e https://music.163.com`，iOS端只能播9秒
使用严格模式`$node app.js -p 8080:8081 -s -e https://music.163.com`，yt-dlp能搜索到链接并替换歌曲，但是会不断搜索，在`81.70.126.110:80`（酷我）与`218.200.160.55:443`（咪咕）间反复横跳超时，最终是iOS端无法播放

**Comment by rcy17** [comment]
截止2024年2月更新的0.27.5版本，这一问题仍然存在，我观测到了在仅启用 ytdlp 源时在 windows 上可以正常工作，但是在 MacOS 上会得到只能播放9秒的版本。

**Comment by forrany** [comment]
同样遇到此问题，似乎使用海外服务器有点无解。。。

现在我这边用大陆的服务器了

**Comment by gavinliuisme** [comment]
手上只有黑裙6.0 只有node 12，只能去改precompiled/app.js， 成功了

**Comment by uxfion** [comment]
我也是只有9s，但是看后台获取到的直链是完整的全部歌曲，mac客户端
<img width="185" alt="image" src="https://github.com/UnblockNeteaseMusic/server/assets/44778029/80f8a8a6-7f37-4ff8-bc4e-b6b27d50aa40">

**Comment by Kyle-Kyle** [comment]
根据yt-dlp的log: WARNING: xxxxx: writing DASH m4a. Only some players support this container. Install ffmpeg to fix this automatically， 应该是youtube那边的问题。
把音乐用yt-dlp下载下来（diginal ocean上大概3秒）在服务器上架个RangeHTTPServer就完了

**Comment by ZhaofengWu** [comment]
@1715173329 请问 close 了是因为没办法 fix 吗？

**Comment by 1715173329** [comment]
这是 youtube 和 macos 设备之间的问题，不应由 unm 处理，也很难处理。
