### ISSUE TITLE
QQ音源搜索歌曲错误

### ISSUE THREAD

**Issue by qilinxinan** [UnblockNeteaseMusic/server#779]
Docker部署，运行参数（QQ_COOKIE填写做了隐藏）
docker run --restart=always --name yunmusic -e NO_CACHE=true -e LOG_LEVEL=debug -e QQ_COOKIE="uin=xx;qm_keyst=xx" -p 1234:8080 pan93412/unblock-netease-music-enhanced -o qq
已开通了豪华绿砖，使用QQ音源会有如下报错信息。

DEBUG: (request) Start requesting https://c.y.qq.com/soso/fcgi-bin/client_search_cp?ct=24&qqmusic_ver=1298&remoteplace=txt.yqq.center&t=0&aggr=1&cr=1&catZhida=1&lossless=0&flag_qc=0&p=1&n=20&w=%E6%9B%BE%E7%BB%8F%E4%BD%A0%E8%AF%B4%20-%20%E8%B5%B5%E4%B9%83%E5%90%89&g_tk=5381&jsonpCallback=MusicJsonCallback10005317669353331&loginUin=0&hostUin=0&format=jsonp&inCharset=utf8&outCharset=utf-8&notice=0&platform=yqq&needNewCode=0
ERROR: (provider/match) Unexpected end of JSON input
    SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at /app/app.js:3113:65
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async getAudioFromSource (/app/app.js:2307:23)
        at async Promise.any (index 0)
        at async match (/app/app.js:2322:23)
        at async Promise.all (index 0)
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected

**Comment by qilinxinan** [comment]
找到原因了，是因为服务器不是大陆造成的，被屏蔽了。
