### ISSUE TITLE
PC版2.10.2版本无法代理，工具报错如下

### ISSUE THREAD

**Issue by LiuXiaohuanhh** [UnblockNeteaseMusic/server#780]
PC端网易云版本为2.10.1和2.10.2时无法正常使用代理，已安装证书，启动命令为 node app.js 未添加任何参数，会有如下报错：

ERROR: (hook) A error occurred in hook.request.after when hooking https://music.163.com/eapi/batch.
    Error: error:1C80006B:Provider routines::wrong final block length
        at Decipheriv.final (node:internal/crypto/cipher:193:29)
        at decrypt (C:\Users\name\server-enhanced\precompiled\app.js:420:18)
        at Object.decrypt (C:\Users\name\server-enhanced\precompiled\app.js:433:28)
        at C:\Users\name\server-enhanced\precompiled\app.js:869:65
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    library: Provider routines
    reason: wrong final block length
    code: ERR_OSSL_WRONG_FINAL_BLOCK_LENGTH

**Comment by 1715173329** [comment]
Should be fixed by f0d4a652b4096c644919d909c57927fb0d9e1e14.
