### ISSUE TITLE
周杰伦播不了了 用的pm2启动的

### ISSUE THREAD

**Issue by xiaopebaka** [UnblockNeteaseMusic/server#788]
0|netease  | ERROR: (hook) All promises were rejected
0|netease  |     AggregateError: All promises were rejected
0|netease  | ERROR: (provider/match) Unexpected end of JSON input
0|netease  |     SyntaxError: Unexpected end of JSON input
0|netease  |         at JSON.parse (<anonymous>)
0|netease  |         at /home/pi/Documents/server/precompiled/app.js:274:408
0|netease  |         at runMicrotasks (<anonymous>)
0|netease  |         at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|netease  |         at async CacheStorage.cache (/home/pi/Documents/server/precompiled/app.js:13:22)
0|netease  |         at async getAudioFromSource (/home/pi/Documents/server/precompiled/app.js:187:17)
0|netease  |         at async Promise.any (index 0)
0|netease  |         at async module.exports (/home/pi/Documents/server/precompiled/app.js:207:234)
0|netease  |         at async Promise.all (index 0)

在.env 里写了QQ_COOKIE

**Comment by 1715173329** [comment]
#779
Use `migu` instead.

**Comment by SenLief** [comment]
kuwo有周杰伦的源，用kuwo就可以了。

**Comment by xiaopebaka** [comment]
> kuwo有周杰伦的源，用kuwo就可以了。

啥都用不了  之前不用别的源还能听 现在周杰伦 tank啥的 都听不了 出上面发的错误
不是qq版权的 倒是可以听

**Comment by SenLief** [comment]
最近我这也是一直报错，不知为何、

**Comment by xiaopebaka** [comment]
> 最近我这也是一直报错，不知为何、

腾讯放大招了

**Comment by 1715173329** [comment]
QQ search API is now fixed.
