### ISSUE TITLE
Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length

### ISSUE THREAD

**Issue by pan93412** [UnblockNeteaseMusic/server#79]
```
Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipheriv.final (node:internal/crypto/cipher:193:29)
    at decrypt (/Users/pan93412/UnblockNeteaseMusic/src/crypto.js:12:58)
    at Object.decrypt (/Users/pan93412/UnblockNeteaseMusic/src/crypto.js:23:22)
    at /Users/pan93412/UnblockNeteaseMusic/src/hook.js:154:53
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'wrong final block length',
  code: 'ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH'
} https://music.163.com/eapi/album/privilege
```

**Comment by 1715173329** [comment]
I found a another error:
```
Error: error:02015016:system library:ioctl:Invalid argument
    at Decipheriv.createCipherBase (internal/crypto/cipher.js:103:19)
    at Decipheriv.createCipherWithIV (internal/crypto/cipher.js:121:20)
    at new Decipheriv (internal/crypto/cipher.js:262:22)
    at Object.createDecipheriv (crypto.js:131:10)
    at decrypt (/usr/share/unblockneteasemusic/core/src/crypto.js:11:26)
    at Object.decrypt (/usr/share/unblockneteasemusic/core/src/crypto.js:23:22)
    at /usr/share/unblockneteasemusic/core/src/hook.js:101:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  library: 'system library',
  function: 'ioctl',
  reason: 'Invalid argument',
  code: 'ERR_OSSL_SYS_INVALID_ARGUMENT'
} http://music.163.com/eapi/pl/count
```

**Comment by zengxiaoliang** [comment]
另一种异常


MITM > music.163.com (ssl)
TypeError: Cannot set property 'flag' of undefined
    at inject (/Users/zeng/WebProject/UnblockNeteaseMusic/src/hook.js:284:13)
    at tryMatch (/Users/zeng/WebProject/UnblockNeteaseMusic/src/hook.js:327:12)
    at /Users/zeng/WebProject/UnblockNeteaseMusic/src/hook.js:161:50
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) https://music.163.com/eapi/song/enhance/player/url

**Comment by pan93412** [comment]
node版本：v12.20.1
启动方式：node /root/UnblockNeteaseMusic/app.js -p 6200:6201 -s

Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
at Decipheriv.final (internal/crypto/cipher.js:172:29)
at decrypt (/root/UnblockNeteaseMusic/src/crypto.js:12:58)
at Object.decrypt (/root/UnblockNeteaseMusic/src/crypto.js:23:24)
at /root/UnblockNeteaseMusic/src/hook.js:226:25
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5) {
library: 'digital envelope routines',
function: 'EVP_DecryptFinal_ex',
reason: 'wrong final block length',
code: 'ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH'
} https://music.163.com/eapi/album/privilege

**Comment by 4860575** [comment]
commit 26ad320858e598dc1a70387c05503a412f9078d1 (HEAD, origin/enhanced, origin/HEAD)
服务端：centos 7.9
nodejs：v14.16.0
启动方式：ENABLE_FLAC=true node /root/UnblockNeteaseMusic-b/app.js -p 5200:5201 -s >>/tmp/flac.log 2>&1 &
客户端：Mac os 1.5.10
错误日志如下：
[root@VM-0-4-centos ~]# tail -F /tmp/flac.log 
    at Object.decrypt (/root/UnblockNeteaseMusic-b/src/crypto.js:23:24)
    at /root/UnblockNeteaseMusic-b/src/hook.js:228:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'wrong final block length',
  code: 'ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH'
} https://music.163.com/eapi/v3/song/detail
MITM > music.163.com (ssl)
TUNNEL > localhost:5201
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
TUNNEL > localhost:5201
TUNNEL > localhost:5201
TUNNEL > localhost:5201
MITM > music.163.com (ssl)
TUNNEL > localhost:5201
TUNNEL > localhost:5201
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipheriv.final (internal/crypto/cipher.js:174:29)
    at decrypt (/root/UnblockNeteaseMusic-b/src/crypto.js:12:58)
    at Object.decrypt (/root/UnblockNeteaseMusic-b/src/crypto.js:23:24)
    at /root/UnblockNeteaseMusic-b/src/hook.js:228:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'wrong final block length',
  code: 'ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH'
} https://music.163.com/eapi/v3/song/detail
MITM > music.163.com (ssl)

**Comment by 1715173329** [comment]
看起来像是网易云音乐服务器问题，目前暂时没有再次出现此类错误。

**Comment by pan93412** [comment]
試圖 debug 了一下。看起來是網易雲那邊的 SSL 加密方式怪怪的。

可能需要重新逆向。
