### ISSUE TITLE
2.9.10出错

### ISSUE THREAD

**Issue by SenLief** [UnblockNeteaseMusic/server#796]
错误信息
ERROR: (provider/match) Invalid URL
    TypeError [ERR_INVALID_URL]: Invalid URL
        at new NodeError (node:internal/errors:372:5)
        at URL.onParseError (node:internal/url:553:9)
        at new URL (node:internal/url:629:5)
        at single (/home/senlief/UnblockNeteaseMusic/precompiled/app.js:2547:25)
        at /home/senlief/UnblockNeteaseMusic/precompiled/app.js:2558:55
        at Array.map (<anonymous>)
        at track (/home/senlief/UnblockNeteaseMusic/precompiled/app.js:2558:41)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async getAudioFromSource (/home/senlief/UnblockNeteaseMusic/precompiled/app.js:2307:23)
    input: undefined
    code: ERR_INVALID_URL
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected

网易云版本
2.9.10

启动命令
LOG_LEVEL=debug node app.js -p 1149:1148 -o migu -s -e https://music.163.com -f 59.111.19.33

**Comment by 1715173329** [comment]
由于 migu api 变动，现在需要指定 MIGU_COOKIE，详细参见 readme。
