### ISSUE TITLE
mac 解锁错误，日志如下

### ISSUE THREAD

**Issue by guider** [UnblockNeteaseMusic/server#833]
ERROR: (hook) A error occurred in hook.request.after when hooking https://music.163.com/eapi/batch.
    Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
        at Decipheriv.final (internal/crypto/cipher.js:174:29)
        at decrypt (/usr/share/unblockneteasemusic/core/app.js:50:56)
        at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:52:90)
        at /usr/share/unblockneteasemusic/core/app.js:98:163
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
    library: digital envelope routines
    function: EVP_DecryptFinal_ex
    reason: wrong final block length
    code: ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH

**Comment by 1715173329** [comment]
#832

**Comment by ohperhaps** [comment]
same issue
