### ISSUE TITLE
hook error: ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH

### ISSUE THREAD

**Issue by 1715173329** [UnblockNeteaseMusic/server#972]
### Bug 描述

hook error 再次出现，暂不清楚由何原因导致，可能与之前一样是编码问题。

### 日志内容

```
ERROR: (hook) A error occurred in hook.request.after when hooking https://music.163.com/weapi/v3/song/detail?csrf_token=.
    Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
        at Decipheriv.final (node:internal/crypto/cipher:193:29)
        at decrypt (/usr/share/unblockneteasemusic/core/app.js:51:56)
        at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:53:90)
        at /usr/share/unblockneteasemusic/core/app.js:100:164
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    library: digital envelope routines
    function: EVP_DecryptFinal_ex
    reason: wrong final block length
    code: ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH
```

### 网易云音乐版本号

2.10.5+

### 操作系统

Windows / iOS / macOS

### 条款

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint（仅 macOS 或 iOS）。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意开发者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
Fixed by #1305
